import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/components/providers/socket-providers";
import { QueryProvider } from "@/components/providers/query-provider";
import { ToastContainer } from "@/components/ui/toast-container";
import localFont from "next/font/local";
import { ConfirmDialogProvider } from "@/components/providers/confirm-dialog-provider";

const pretendard = localFont({
  src: "../public/fonts/Pretendard.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} font-pretendard`}>
        <SocketProvider>
          <QueryProvider>
            {children}
            <ToastContainer />
            <ConfirmDialogProvider />
          </QueryProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
