name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.1"

      - name: Create env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env

      - name: Install and Build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          npm install
          npm run build

      - name: Zip the build files
        run: |
          zip -r build.zip .next .env package.json package-lock.json

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key build.zip ${USER}@${HOST}:~/chat-app/
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd ~/chat-app
            unzip -o build.zip
            npm install --omit=dev
            pm2 delete all || true
            pm2 start "npm run start" --name "chat-app"
          '
