name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # 1. 코드 체크아웃

      - name: Use Node.js
        uses: actions/setup-node@v2 # 2. Node.js 설정
        with:
          node-version: "18.19.1"

      - name: Set environment variables # 환경변수 설정
        run: echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd ~/chat-app
            git pull origin main
            npm install
            npm run build
            pm2 delete all || true
            pm2 start "npm run start" --name "chat-app"
          '
