name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.1"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" | tr -d '\r' | sed 's/\\n/\n/g' > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r build/* ${USER}@${HOST}:~/chat-app
          ssh -vvv -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd ~/chat-app
            npm install
            npm ci
            pm2 delete all || true
            pm2 start "npm run start" --name "chat-app"
          '
