name: Deploy built app to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.1"

      - name: Set environment variables # 환경변수 설정
        run: echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Install and Build
        run: |
          npm install
          npm run build
          zip -r build.zip .next public package.json .env .env.local

      - name: Copy build files to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key build.zip ${USER}@${HOST}:~/chat-app/

      - name: Deploy on EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd ~/chat-app
            unzip -o build.zip
            npm install --omit=dev
            pm2 delete all || true
            pm2 start "npm run start" --name "chat-app"
          '
