name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.1"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Create deployment package
        run: |
          tar -czf deploy.tar.gz .next node_modules package.json package-lock.json

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          # 기존 배포 파일 백업
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd ~/chat-app
            if [ -d ".next" ]; then
              mv .next .next_backup
            fi'

          # 새로운 배포 파일 전송
          scp -o StrictHostKeyChecking=no -i private_key deploy.tar.gz ${USER}@${HOST}:~/chat-app/

          # 배포 및 서버 재시작
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            cd ~/chat-app
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            pm2 delete all || true
            pm2 start "npm run start" --name "chat-app"
            
            # 백업 삭제
            if [ -d ".next_backup" ]; then
              rm -rf .next_backup
            fi'
